locales:
  krl:
    name: Karelian Keyboards
    description: >-
      Mobile OS keyboards for the Karelian language from the Divvun group
      at UiT.
  en:
    name: Karelian Keyboards
    description: >-
      Mobile OS keyboards for the Karelian language from the Divvun group
      at UiT.
  nb:
    name: Karelian tastatur
    description: Mobiltastatur for Karelian fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
